### ISSUE TITLE
Set c++ standard to c++17

### ISSUE THREAD

**Issue by firesurfer** [leggedrobotics/soem_interface#6]
@tomlankhorst and @jungerj 
I think we could push the c++ standard to c++17. 
The oldest gcc version one uses to compile this repo should gcc 7.2 (which is default in ubuntu18). gcc 7.2 fully supports c++17
See: https://gcc.gnu.org/projects/cxx-status.html

**Comment by tomlankhorst** [comment]
But ROS does not support it. So you can only use C++17 internally, not in publicly exposed headers. Use C++ 14 there. 

You can set a private compile feature cxx_std_17 in CMake.

**Comment by firesurfer** [comment]
I see. Lets keep it like it is at the moment.
